#define SHARED_BONES_IN_VERTEX			6
#define SHARED_BONES_IN_SKELETON		100

#define SHARED_LIGHTS_CAPACITY			10

#define SHARED_LIGHT_TYPE_EMPTY			-1
#define SHARED_LIGHT_TYPE_DIRECTIONAL	0
#define SHARED_LIGHT_TYPE_POINT			1

#define SHARED_ATTENUATION_CONSTANT		1.0f
#define SHARED_ATTENUATION_LINEAR		0.014
#define SHARED_ATTENUATION_QUADRATIC	0.0007