#define SHARED_BONES_IN_VERTEX			6
#define SHARED_BONES_IN_SKELETON		100

#define SHARED_LIGHTS_CAPACITY			30

#define SHARED_LIGHT_TYPE_EMPTY			-1
#define SHARED_LIGHT_TYPE_AMBIENT		0
#define SHARED_LIGHT_TYPE_DIRECTIONAL	1
#define SHARED_LIGHT_TYPE_POINT			2
#define SHARED_LIGHT_TYPE_PROJECTOR		3

#define SHARED_ATTENUATION_CONSTANT		1.0f
#define SHARED_ATTENUATION_LINEAR		0.014f
#define SHARED_ATTENUATION_QUADRATIC	0.0007f